### ISSUE TITLE
2 more requirements

### ISSUE THREAD

**Issue by lupa18** [erseco/alpine-moodle#10]
Hi ! it appears 2 configs are missing: 

1. php-sodium

![imagen](https://user-images.githubusercontent.com/463429/139742812-1124fab9-ff52-4c77-a310-bf15667a1cc7.png)

2. max_input_vars

![imagen](https://user-images.githubusercontent.com/463429/139742872-032b9210-fe6f-4f21-92e3-c19746597f95.png)

could you chek them for the next build?

thanks in advance !

**Comment by erseco** [comment]
You can try the `beta` labeled container to check this
