### ISSUE TITLE
config.php writable warning 

### ISSUE THREAD

**Issue by lupa18** [erseco/alpine-moodle#12]
Hola @erseco ! 

I'm testing your beta and having this warning: 

![imagen](https://user-images.githubusercontent.com/463429/144463463-23b79341-e575-4dc8-b250-c83b3e56e39c.png)

**Comment by erseco** [comment]
Can you check if you are using a clean environment? I just check the beta version and the permissions are correct
<img width="956" alt="Captura de pantalla 2021-12-02 a las 21 55 40" src="https://user-images.githubusercontent.com/1876752/144510182-139b657c-2ffb-474f-9842-60dd69eb8822.png">

Check that  the script `02-configure-moodle.sh` is forcing the correct file permissions
```
    # Avoid writing the config file
    chmod 444 config.php
```
