### ISSUE TITLE
Método de actualización

### ISSUE THREAD

**Issue by lupa18** [erseco/alpine-moodle#13]
Hola @erseco !

Como estás? Estoy viendo que hay una nueva actualización y de M, y me pregunto cuál sería la forma más interesante de hacerlo luego de que la beta tiene persistencia en toda la carpeta html. 

La interfaz de M me indica que está disponible la 3.11.5+ pero no conozco cómo actualizar desde allí. Por lo tanto hice un build y descargó algo, y borré contenedores pero al volver a levantar obviamente, está la persistencia en /var/www/html así que sigue la misma versión.  

Luego, intenté usar la CLI, pero me dice lo siguiente: 

```
/var/www/html $ php admin/cli/upgrade.php                                                      
No se necesita actualizar la versión instalada 3.11.4+ (Build: 20211201) (2021051704.06).
```

(además no estoy corriendo desde la UID que indica el tutorial: https://docs.moodle.org/311/en/Administration_via_command_line#Upgrading )

Entonces entiendo que para correr 'update' primero debo colocar el nuevo código en lugar del viejo, entonces ¿cómo te parece la mejor forma de actualizar?

gracias desde ya!

**Comment by erseco** [comment]
Hello, I just pushed an updated release of the container, you just need to do a `docker-compose pull && docker-compose up -d` to recreate the updated container. Hope it helps :)

**Comment by lupa18** [comment]
Thanks ! I guess it would be the same, because since I have a moodle already running and with persistence over /var/www/html nothing new will affect that folder at build time. 

So I should manually download new moodle inside container and run update.php script (but I guess is not going to work, because inside it I will be a normal user without rights).

**Comment by erseco** [comment]
You don't need special permission to run the update.php script, so you can run it without any problem

Also you can override your persistence files with the new container one running a `docker cp ...` command, I did this before but I don't remember the exactly command
