### ISSUE TITLE
Moodle issue with buffering

### ISSUE THREAD

**Issue by jvinolas** [erseco/alpine-moodle#14]
In moodle I don't get the progress update of events when a moodle long script is executing and giving back events to show in the page. I'll only get those at the end of the process. It happens for example when upgrading database with modules.

I think it is related to nginx/php-fpm buffering configuration. How can I modify this behaviour?

**Comment by erseco** [comment]
Please, tell me which long script are you running to reproduce the issue. Thanks!

**Comment by jvinolas** [comment]
After testing, it was the nginx gzip compression. Disabling it through the same php with ```header('Content-Encoding: none');``` and filling the buffer after each echo with ```echo str_repeat(' ',1024*64);``` did the trick without modifying any setup.
