### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by aldinokemal** [erseco/alpine-moodle#15]
When i deploy to server i used proxy reverse, my moodle expose port is 4400 than i tried to proxy reverse to this port the result is ERR_TOO_MANY_REDIRECTS

i have changed `SITE_URL=http://mydomain.com`

```
ports:
      - 4400:8080
```

**Comment by erseco** [comment]
Hello, if you expose moodle on port 4400 you should configure the SITE_URL var as `SITE_URL=http://mydomain.com:4400`

Best!

**Comment by aldinokemal** [comment]
i'm forget to set SSL true
