### ISSUE TITLE
how to config url 

### ISSUE THREAD

**Issue by nandar1305** [erseco/alpine-moodle#19]
how to config url/ip to acces moodle from other device??

**Comment by lupa18** [comment]
Hi @nandar1305,

What is your need exactly? Are you using docker compose? Where is your deployment, local machine or an online service?

There is a environment variable called `SITE_URL` that you can use to config URL.

**Comment by erseco** [comment]
As @lupa18 says, please explain a little what are you trying to do, because the possibilities are unlimited :)

**Comment by nandar1305** [comment]
> Hi @nandar1305,
> 
> What is your need exactly? Are you using docker compose? Where is your deployment, local machine or an online service?
> 
> There is a environment variable called `SITE_URL` that you can use to config URL.

i use in docker-compose, and want to acces moodle from other device offline from my laptop.

**Comment by erseco** [comment]
In that case, you just need to enter to your device by its IP address: http://<ip-address>:8080

It is possible that you need to open the 8080 port in your firewall to access it, but this is more related to your system configuration and not about the moodle install, so I will close the issue. Best!
