### ISSUE TITLE
migrating an existent Moodle to this docker container

### ISSUE THREAD

**Issue by ccomincini** [erseco/alpine-moodle#20]
Hi, thank you for sharing your work.
I've seen this is a container that installs moodle at startup.
I have an existing moodle installation (apache-PHP-MariaDB) and want to migrate to docker.
I want to use your Nginx-PHP image with a MariaDB database. I can add a service in docker-compose.yml  for MariaDB that uses my migrated DB and mount var/lib/mysql as a volume, but I don't know how to run my actual 4.1 installation in your image.
sorry for borrowing, I'm a docker rookie. May you help me, please?
Thanks 
Carlo

**Comment by erseco** [comment]
IMHO, migrating direct `/var/lib/mysql` files can be a little bit messy. Seems easier if you dump your current database and import in the new Dockerized one, or best if you export your moodle courses directly. Let me know which option do you prefer, and I will try to help you.

**Comment by erseco** [comment]
Hi @ccomincini, 

Just wanted to let you know that I'm closing the GitHub issue we've been discussing, since we haven't received any additional data to move forward with a solution. If you have any updates or information to share in the future, feel free to reopen the issue.

Best regards
