### ISSUE TITLE
Extensions persistence

### ISSUE THREAD

**Issue by lupa18** [erseco/alpine-moodle#9]
Hi ! how do you recommend configuring persistence on extensions?

I added 2 or 3 extensions and after the container removal and re-creation it appears "disappeared from disk".

**Comment by erseco** [comment]
The easiest way to add persistence on extensions is binding the `mod` directory to a data volume or to your filesystem in the `docker-compose.yml` file

**Comment by erseco** [comment]
I added a volume to the mod directory, you can try the `beta` labeled container to check if it works. Best regards!

**Comment by lupa18** [comment]
I was trying to figure it, but it seems to be more problematic, since installation folder could be one of several: 
https://docs.moodle.org/311/en/Installing_plugins#Installing_manually_at_the_server

or even more: https://docs.moodle.org/dev/Plugin_types

**Comment by erseco** [comment]
There are two approaches:
- Add a volume per each directory, that will be complicated to maintain
- Persist the entire `/var/www/html` directory, that I'm trying now on beta container
Please, try it and tell your thoughts

Best regards!
